### ISSUE TITLE
Ajouter un produit au panier

### ISSUE THREAD

**Issue by terence-meunier** [terence-meunier/bookdev#26]
- [x] Faire un bouton "Ajouter au panier" dans la page du produit
- [x] initialiser le panier (créer la variable de session)
- [x] Création d'un faux panier
- [x] Ajouter des vrais produits dans le panier (bouton ajouter produit)

**Comment by cbouvat** [comment]
C'est plus que "ajouter au panier", il faudrait découper en différentes user stories
